trigger: 
 branches:
   include:
     - master

pool: my-pool
name: docker-agent

stages:
  - stage: Create Infra
    displayName: create a Dev VM
    jobs:
      - job: init
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env'
            backendServiceArm: 'infra'
            backendAzureRmStorageAccountName: 'beltfstateprod'
            backendAzureRmContainerName: 'tfstatecontainer'
            backendAzureRmKey: 'dev-terraform.tfstate'

        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env'
            environmentServiceNameAzureRM: 'infra'

        - task: TerraformTask@5
          displayName: terraform apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env'
        